onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

overrides:
  "freelens": ../freelens/freelens-1.5.0-0.tgz
  "@freelensapp/animate": ../freelens/freelensapp-animate-1.5.0-0.tgz
  "@freelensapp/application": ../freelens/freelensapp-application-1.5.0-0.tgz
  "@freelensapp/application-for-electron-main": ../freelens/freelensapp-application-for-electron-main-1.5.0-0.tgz
  "@freelensapp/button": ../freelens/freelensapp-button-1.5.0-0.tgz
  "@freelensapp/cluster-settings": ../freelens/freelensapp-cluster-settings-1.5.0-0.tgz
  "@freelensapp/cluster-sidebar": ../freelens/freelensapp-cluster-sidebar-1.5.0-0.tgz
  "@freelensapp/computed-channel": ../freelens/freelensapp-computed-channel-1.5.0-0.tgz
  "@freelensapp/core": ../freelens/freelensapp-core-1.5.0-0.tgz
  "@freelensapp/ensure-binaries": ../freelens/freelensapp-ensure-binaries-1.5.0-0.tgz
  "@freelensapp/error-boundary": ../freelens/freelensapp-error-boundary-1.5.0-0.tgz
  "@freelensapp/event-emitter": ../freelens/freelensapp-event-emitter-1.5.0-0.tgz
  "@freelensapp/extensions": ../freelens/freelensapp-extensions-1.5.0-0.tgz
  "@freelensapp/feature-core": ../freelens/freelensapp-feature-core-1.5.0-0.tgz
  "@freelensapp/generate-tray-icons": ../freelens/freelensapp-generate-tray-icons-1.5.0-0.tgz
  "@freelensapp/icon": ../freelens/freelensapp-icon-1.5.0-0.tgz
  "@freelensapp/jest": ../freelens/freelensapp-jest-1.5.0-0.tgz
  "@freelensapp/json-api": ../freelens/freelensapp-json-api-1.5.0-0.tgz
  "@freelensapp/keyboard-shortcuts": ../freelens/freelensapp-keyboard-shortcuts-1.5.0-0.tgz
  "@freelensapp/kube-api": ../freelens/freelensapp-kube-api-1.5.0-0.tgz
  "@freelensapp/kube-api-specifics": ../freelens/freelensapp-kube-api-specifics-1.5.0-0.tgz
  "@freelensapp/kube-object": ../freelens/freelensapp-kube-object-1.5.0-0.tgz
  "@freelensapp/kubectl-versions": ../freelens/freelensapp-kubectl-versions-1.5.0-0.tgz
  "@freelensapp/kubernetes-client-node": ../freelens/freelensapp-kubernetes-client-node-1.5.0-0.tgz
  "@freelensapp/legacy-extensions": ../freelens/freelensapp-legacy-extensions-1.5.0-0.tgz
  "@freelensapp/legacy-global-di": ../freelens/freelensapp-legacy-global-di-1.5.0-0.tgz
  "@freelensapp/list-layout": ../freelens/freelensapp-list-layout-1.5.0-0.tgz
  "@freelensapp/logger": ../freelens/freelensapp-logger-1.5.0-0.tgz
  "@freelensapp/messaging": ../freelens/freelensapp-messaging-1.5.0-0.tgz
  "@freelensapp/messaging-fake-bridge": ../freelens/freelensapp-messaging-fake-bridge-1.5.0-0.tgz
  "@freelensapp/messaging-for-main": ../freelens/freelensapp-messaging-for-main-1.5.0-0.tgz
  "@freelensapp/messaging-for-renderer": ../freelens/freelensapp-messaging-for-renderer-1.5.0-0.tgz
  "@freelensapp/metrics": ../freelens/freelensapp-metrics-1.5.0-0.tgz
  "@freelensapp/node-fetch": ../freelens/freelensapp-node-fetch-1.5.0-0.tgz
  "@freelensapp/notifications": ../freelens/freelensapp-notifications-1.5.0-0.tgz
  "@freelensapp/openid-client": ../freelens/freelensapp-openid-client-1.5.0-0.tgz
  "@freelensapp/prometheus": ../freelens/freelensapp-prometheus-1.5.0-0.tgz
  "@freelensapp/random": ../freelens/freelensapp-random-1.5.0-0.tgz
  "@freelensapp/react-application": ../freelens/freelensapp-react-application-1.5.0-0.tgz
  "@freelensapp/react-testing-library-discovery": ../freelens/freelensapp-react-testing-library-discovery-1.5.0-0.tgz
  "@freelensapp/resizing-anchor": ../freelens/freelensapp-resizing-anchor-1.5.0-0.tgz
  "@freelensapp/resource-templates": ../freelens/freelensapp-resource-templates-1.5.0-0.tgz
  "@freelensapp/routing": ../freelens/freelensapp-routing-1.5.0-0.tgz
  "@freelensapp/run-many": ../freelens/freelensapp-run-many-1.5.0-0.tgz
  "@freelensapp/semver": ../freelens/freelensapp-semver-1.5.0-0.tgz
  "@freelensapp/spinner": ../freelens/freelensapp-spinner-1.5.0-0.tgz
  "@freelensapp/startable-stoppable": ../freelens/freelensapp-startable-stoppable-1.5.0-0.tgz
  "@freelensapp/test-utils": ../freelens/freelensapp-test-utils-1.5.0-0.tgz
  "@freelensapp/tooltip": ../freelens/freelensapp-tooltip-1.5.0-0.tgz
  "@freelensapp/typescript": ../freelens/freelensapp-typescript-1.5.0-0.tgz
  "@freelensapp/utilities": ../freelens/freelensapp-utilities-1.5.0-0.tgz
  "@freelensapp/webpack": ../freelens/freelensapp-webpack-1.5.0-0.tgz
